-- Disable foreign key constraints to avoid conflicts during deletion
ALTER TABLE Messages NOCHECK CONSTRAINT ALL;
ALTER TABLE Reviews NOCHECK CONSTRAINT ALL;
ALTER TABLE Requests NOCHECK CONSTRAINT ALL;
ALTER TABLE Favorites NOCHECK CONSTRAINT ALL;
ALTER TABLE Content_Genre NOCHECK CONSTRAINT ALL;
ALTER TABLE Content NOCHECK CONSTRAINT ALL;
ALTER TABLE AdminPanelLogs NOCHECK CONSTRAINT ALL;
ALTER TABLE Communities NOCHECK CONSTRAINT ALL;
ALTER TABLE Books NOCHECK CONSTRAINT ALL;
ALTER TABLE Movies NOCHECK CONSTRAINT ALL;
ALTER TABLE Games NOCHECK CONSTRAINT ALL;

-- Delete data from all tables in order
DELETE FROM Messages;
DELETE FROM Reviews;
DELETE FROM Requests;
DELETE FROM Favorites;
DELETE FROM Content_Genre;
DELETE FROM Content;
DELETE FROM AdminPanelLogs;
DELETE FROM Communities;
DELETE FROM Books;
DELETE FROM Movies;
DELETE FROM Games;
DELETE FROM Users;
DELETE FROM Genres;

-- Re-enable foreign key constraints
ALTER TABLE Messages CHECK CONSTRAINT ALL;
ALTER TABLE Reviews CHECK CONSTRAINT ALL;
ALTER TABLE Requests CHECK CONSTRAINT ALL;
ALTER TABLE Favorites CHECK CONSTRAINT ALL;
ALTER TABLE Content_Genre CHECK CONSTRAINT ALL;
ALTER TABLE Content CHECK CONSTRAINT ALL;
ALTER TABLE AdminPanelLogs CHECK CONSTRAINT ALL;
ALTER TABLE Communities CHECK CONSTRAINT ALL;
ALTER TABLE Books CHECK CONSTRAINT ALL;
ALTER TABLE Movies CHECK CONSTRAINT ALL;
ALTER TABLE Games CHECK CONSTRAINT ALL;
GO