-- Generated by Oracle SQL Developer Data Modeler 24.3.0.240.1210
--   at:        2025-05-07 10:54:52 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE AdminPanelLogs 
    (
     LogID INTEGER NOT NULL , 
     AdminUserID INTEGER NOT NULL , 
     ActionDescription VARCHAR (max) , 
     ActionDate DATE 
    )
GO

ALTER TABLE AdminPanelLogs ADD CONSTRAINT AdminPanelLogs_PK PRIMARY KEY CLUSTERED (LogID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ChatRooms 
    (
     ChatID INTEGER NOT NULL , 
     ChatName VARCHAR (30) 
    )
GO

ALTER TABLE ChatRooms ADD CONSTRAINT ChatRooms_PK PRIMARY KEY CLUSTERED (ChatID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE ChatRooms ADD CONSTRAINT ChatRooms__UN UNIQUE NONCLUSTERED (ChatName)
GO

CREATE TABLE Content 
    (
     ContentID INTEGER NOT NULL , 
     Title VARCHAR (255) NOT NULL , 
     ContentType VARCHAR (5) , 
     Description VARCHAR (300) , 
     ReleaseDate DATE , 
     Rating DECIMAL (2,1) , 
     addedByUserID INTEGER 
    )
GO

ALTER TABLE Content ADD CONSTRAINT Content_PK PRIMARY KEY CLUSTERED (ContentID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Content ADD CONSTRAINT Content_CK_1 CHECK ( ContentType in ('Film', 'Series', 'Game', 'Book') ) 
GO


ALTER TABLE Content ADD CONSTRAINT Content_CK_Rating CHECK ( Rating BETWEEN 0 AND 10
 ) 
GO

CREATE TABLE Content_Genre 
    (
     GenreID INTEGER NOT NULL , 
     ContentID INTEGER NOT NULL 
    )
GO

CREATE TABLE Favorites 
    (
     FavoriteID INTEGER NOT NULL , 
     UserID INTEGER NOT NULL , 
     ContentID INTEGER , 
     ChatRooms_ChatID INTEGER 
    )
GO

ALTER TABLE Favorites ADD CONSTRAINT Favorites_PK PRIMARY KEY CLUSTERED (FavoriteID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Genres 
    (
     GenreID INTEGER NOT NULL , 
     Name VARCHAR (20) 
    )
GO

ALTER TABLE Genres ADD CONSTRAINT Genres_PK PRIMARY KEY CLUSTERED (GenreID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Moderation 
    (
     ModerationID INTEGER NOT NULL , 
     UserID INTEGER NOT NULL , 
     Status VARCHAR (50) , 
     Description VARCHAR (500) 
    )
GO

ALTER TABLE Moderation ADD CONSTRAINT Moderation_PK PRIMARY KEY CLUSTERED (ModerationID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Moderation ADD CONSTRAINT Moderation_CK_1 CHECK ( Status IN ('Pending', 'Approved', 'Rejected')
 ) 
GO

CREATE TABLE Reviews 
    (
     ReviewID INTEGER NOT NULL , 
     UserID INTEGER NOT NULL , 
     ContentID INTEGER NOT NULL , 
     Rating DECIMAL (2,1) , 
     Comment VARCHAR (max) , 
     ReviewDate DATE 
    )
GO

ALTER TABLE Reviews ADD CONSTRAINT Reviews_PK PRIMARY KEY CLUSTERED (ReviewID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Reviews ADD CONSTRAINT Reviews_CK_1 CHECK ( Rating Between 0 and 10 ) 
GO

CREATE TABLE UserChatRooms 
    (
     UserID INTEGER NOT NULL , 
     ChatID INTEGER NOT NULL 
    )
GO

CREATE TABLE Users 
    (
     UserID INTEGER NOT NULL , 
     Username VARCHAR (25) , 
     Email VARCHAR (254) , 
     PasswordHash VARCHAR (255) , 
     UserType VARCHAR (5) 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    UQ_Users_Usernamev1 ON Users 
    ( 
     Username , 
     Email 
    ) 
GO

ALTER TABLE Users ADD CONSTRAINT Users_PK PRIMARY KEY CLUSTERED (UserID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE Users ADD CONSTRAINT CHK_UserType CHECK ( UserType IN ('User', 'Admin')
 ) 
GO

ALTER TABLE AdminPanelLogs 
    ADD CONSTRAINT AdminPanelLogs_Users_FK FOREIGN KEY 
    ( 
     AdminUserID
    ) 
    REFERENCES Users 
    ( 
     UserID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Content_Genre 
    ADD CONSTRAINT Content_FK FOREIGN KEY 
    ( 
     ContentID
    ) 
    REFERENCES Content 
    ( 
     ContentID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Content 
    ADD CONSTRAINT Content_Users_FK FOREIGN KEY 
    ( 
     addedByUserID
    ) 
    REFERENCES Users 
    ( 
     UserID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Favorites 
    ADD CONSTRAINT Favorites_ChatRooms_FK FOREIGN KEY 
    ( 
     ChatRooms_ChatID
    ) 
    REFERENCES ChatRooms 
    ( 
     ChatID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Favorites 
    ADD CONSTRAINT Favorites_Content_FK FOREIGN KEY 
    ( 
     ContentID
    ) 
    REFERENCES Content 
    ( 
     ContentID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Favorites 
    ADD CONSTRAINT Favorites_Users_FK FOREIGN KEY 
    ( 
     UserID
    ) 
    REFERENCES Users 
    ( 
     UserID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Content_Genre 
    ADD CONSTRAINT Genre_FK FOREIGN KEY 
    ( 
     GenreID
    ) 
    REFERENCES Genres 
    ( 
     GenreID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Moderation 
    ADD CONSTRAINT Moderation_Users_FK FOREIGN KEY 
    ( 
     UserID
    ) 
    REFERENCES Users 
    ( 
     UserID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_Content_FK FOREIGN KEY 
    ( 
     ContentID
    ) 
    REFERENCES Content 
    ( 
     ContentID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_Users_FK FOREIGN KEY 
    ( 
     UserID
    ) 
    REFERENCES Users 
    ( 
     UserID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UserChatRooms 
    ADD CONSTRAINT UserChatRooms_ChatRooms_FK FOREIGN KEY 
    ( 
     ChatID
    ) 
    REFERENCES ChatRooms 
    ( 
     ChatID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UserChatRooms 
    ADD CONSTRAINT UserChatRooms_Users_FK FOREIGN KEY 
    ( 
     UserID
    ) 
    REFERENCES Users 
    ( 
     UserID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             1
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
